#[SI] units

# Exponential decay
decay_rate = 1e-15
M1 = 2.7846e30 
M2 = 2.7846e30 
a = 1.496e11
e = 0.1

[integration]
output_points = 100000
use_cotime = true
cotime_a_min = 1e5
cotime_max_time = 1e20
method = "Radau"
decay_type = "exponential"
initial_points_exponent = 6
exponent_offset = 10

[rendering]
width = 1920
height = 1080
fps = 60
tail_length = 200
star_scale = 5.0
memory_gb = 10.0
stride = 1000
