#[SI] units

decay_rate = 1e-2
M1 = 2.7846e30 
M2 = 2.7846e30 
a = 1.496e8
e = 0.1

output_points = 1000000
use_cotime = true
cotime_a_min = 1e5
cotime_max_time = 1e7
method = "Radau"
decay_type = "exponential"

width = 1920
height = 1080
fps = 60
tail_length = 200
star_scale = 5.0
memory_gb = 10.0
stride = 1