decay_rate = 1e-7

#kg
M1 = 2.7846e30
M2 = 2.7846e30

#meters
a = 1.496e8

e = 0.1

[integration]
output_points = 1000000

use_cotime = true

cotime_a_min = 1e5

cotime_max_time = 1e7

method = "Radau"

decay_type = "linear"
